### ISSUE TITLE
Please add versioned releases of the sdk

### ISSUE THREAD

**Issue by wucke13** [seL4/microkit#116]
Currently, https://trustworthy.systems/projects/microkit/tutorial/part0.html just recommends to download `curl -L trustworthy.systems/Downloads/microkit_tutorial/sdk-linux-x64.tar.gz -o sdk.tar.gz`. I would much prefer if the sdk would be versioned, with a list of all previous versions as well:

- trustworthy.systems/Downloads/microkit_tutorial/sdk-linux-x64-0.1.0.tar.gz 
- trustworthy.systems/Downloads/microkit_tutorial/sdk-linux-x64-latest.tar.gz 

Of course it lends itself to have a latest version, and refer to that in the tutorial.

**Comment by Ivan-Velickovic** [comment]
Yes, will do once we have a proper released version which should happen in the near future.

**Comment by Ivan-Velickovic** [comment]
We now have an official release we can point to here, https://github.com/seL4/microkit/releases/tag/1.3.0.

The tutorial will be updated shortly, you can track that in this issue https://github.com/au-ts/microkit_tutorial/issues/8.
