### ISSUE TITLE
Please do not rely on **any** system headers for the microkit API

### ISSUE THREAD

**Issue by wucke13** [seL4/microkit#124]
Currently, there is some dependence on system headers: 

https://github.com/seL4/microkit/blob/17a27354dbdd3a6a60e83442162d48333bd164f7/libmicrokit/include/microkit.h#L11-L12

It would be preferable, if the SDK is truly self-contained; then an empty sysroot would be sufficient to compile. I know, ~~most~~ many cross tool-chains do ship some header files, and often this works else just by leaking in the header from a glibc based toolchain (since we don't actually link something), but I'd much prefer not rely on any of that.

**Comment by Ivan-Velickovic** [comment]
Good point, thank you for bringing this up.

This should now be resolved.
