### ISSUE TITLE
sel4cp mapping to CAMKES primitives

### ISSUE THREAD

**Issue by podhrmic** [seL4/microkit#14]
Hi, if I have an application built on CAMKES, how would I convert such an application to a core-platform based one?
Specifically, is there an example of how to represent `dataports`, `connections` etc in the core-platform?

**Comment by gernotheiser** [comment]
We don't presently have a transition guide, it's on the to-do list...

**Comment by gernotheiser** [comment]
Update: We've got one of our CP-inexperienced (but CAmkES-experienced) engineers to play guinea pig for porting stuff to seL4CP and drafting a guide. Expect something soon.

**Comment by podhrmic** [comment]
@gernotheiser any updates here?

**Comment by gernotheiser** [comment]
We're about to finish a VM example (next week) so should have good sample code then. Writing a guide after that should be straightforward.

**Comment by podhrmic** [comment]
@gernotheiser any news about the VM example?

**Comment by gernotheiser** [comment]
Sorry about the time this is taking. We've got the examples and are in the process of cleaning stuff up and moving from private branches to proper places. Should be done by the end of the week

**Comment by Ivan-Velickovic** [comment]
@podhrmic can this be closed or do you have more questions/concerns?
