### ISSUE TITLE
What is the purpose of the content of a passive server's initialization complete message

### ISSUE THREAD

**Issue by nspin** [seL4/microkit#140]
What is the purpose of the value in this message register?

https://github.com/seL4/microkit/blob/b0fc14311fa4ba2b3ec5a54567b07a7e174cf788/libmicrokit/src/main.c#L107-L112

It isn't used by the monitor:

[1] https://github.com/seL4/microkit/blob/b0fc14311fa4ba2b3ec5a54567b07a7e174cf788/monitor/src/main.c#L444-L456

**Comment by Ivan-Velickovic** [comment]
Looks like it's not necessary. I've opened https://github.com/seL4/microkit/pull/141.

**Comment by Ivan-Velickovic** [comment]
Thank you for point that out.
