### ISSUE TITLE
tool: Use `rustfmt`

### ISSUE THREAD

**Issue by nspin** [seL4/microkit#160]
`rustfmt` would be an easy way to ensure that the tool's code style is consistent and idiomatic.

We could run `cargo fmt --check` in CI.

The cost of starting to use `rustfmt` would be the initial formatting, which would cause merge conflicts with WIP branches.

**Comment by Ivan-Velickovic** [comment]
Is this any different to cargo clippy? Cargo clippy is used at the moment.

**Comment by nspin** [comment]
Yes, `rustfmt` only deals with trivial style concerns, such as whitespace, brackets, semicolons, and import ordering in cases where it doesn't affect the code's meaning.

**Comment by Ivan-Velickovic** [comment]
Two official formatters for the same language ?

Oh well. I guess we can add it as well.

**Comment by Ivan-Velickovic** [comment]
Do you mind adding it in a PR or should I?

**Comment by nspin** [comment]
I’m happy to make a PR.

> Two official formatters for the same language ?

I see it like this: rustfmt deals with how code is laid out in a file, whereas Clippy deals with the code itself. Rustfmt formats at the syntax level, whereas Clippy lints at the semantics level.

At the implementation level, Clippy extends the  rustc driver with its addition lints, whereas rustfmt’s implementation isn’t as integrated with rustc.

**Comment by wucke13** [comment]
To add to that, rustfmt ist a formatter, clippy is a linter.
I'm all in to get this fixed soon, when I prepared my last PR I had to sabotage the autoformat feature of my editor to avoid humongous diffs.

**Comment by lsf37** [comment]
Definitely +1 from me for adding `rustfmt`. It's the standard Rust formatter.

Usually code style would be a TSC decision, but there isn't really any useful alternative out there and the general policy is to have automatic code formatting when possible, so it's fine to just go ahead.
