### ISSUE TITLE
1.3.0 release archive permissions

### ISSUE THREAD

**Issue by podhrmic** [seL4/microkit#163]
Hello all! First, congrats to the new release, that is very exciting!

Second, I noticed the archives (tested the `*.tar.gz` ones) have odd top level permissions. To replicate:
* download the archive and run `tar -xvf microkit-sdk-1.3.0-linux-x86-64.tar.gz` 
* `ls -l` and inspect the extracted folder:
```
dr-xr-xr-x  6 mpodhradsky mpodhradsky     4096 Mar 21  2021  microkit-sdk-1.3.0
-rw-rw-r--  1 mpodhradsky mpodhradsky  7352520 Jul  8 09:46  microkit-sdk-1.3.0-linux-x86-64.tar.gz
```

The directory is not writeable by the owner, which is unusual (I would expect to see `drwxrwxr-x`). 

The same permissions are set for the files as well:
```
microkit-sdk-1.3.0:
total 20
dr-xr-xr-x  2 mpodhradsky mpodhradsky 4096 Mar 21  2021 bin
dr-xr-xr-x 10 mpodhradsky mpodhradsky 4096 Mar 21  2021 board
dr-xr-xr-x  2 mpodhradsky mpodhradsky 4096 Mar 21  2021 doc
-rw-r--r--  1 mpodhradsky mpodhradsky  749 Mar 21  2021 LICENSE.md
dr-xr-xr-x  2 mpodhradsky mpodhradsky 4096 Mar 21  2021 LICENSES
```

While easy to fix, this leads to surprising errors when trying to delete the files, or extract the archive from the desktop UI on Ubuntu. 

Can you confirm you see the same results? I tested this on two different linux OS machines.

**Comment by Ivan-Velickovic** [comment]
This is an expected result, but I agree it is a poor user experience. I thought I fixed this already but looks like I didn't, I've made https://github.com/seL4/microkit/pull/165.

There will be another release, 1.4.0, within the next couple of weeks which will have this fix.

**Comment by Ivan-Velickovic** [comment]
Thanks for reporting the issue.
