### ISSUE TITLE
setvar_vaddr will happily patch the same variable twice

### ISSUE THREAD

**Issue by midnightveil** [seL4/microkit#176]
When the same variable is patched twice, microkit doesn't complain.

Ran into this when accidentally didn't adjust the vaddr var for a different region (came up as the other variable it was supposed to be being 0, which I guess can't do much about)

```xml
    <protection_domain name="client" priority="1" >
        <program_image path="client.elf" />

        <map mr="region_a" vaddr="0x30000000" perms="rw" cached="false" setvar_vaddr="var_a" />
        <map mr="region_b" vaddr="0x30200000" perms="rw" cached="false" setvar_vaddr="var_a" />
    </protection_domain>
```

(It should be `var_b` on the second line)

**Comment by Ivan-Velickovic** [comment]
Fixed in https://github.com/seL4/microkit/commit/57acb4fa5a125cd3add1a097d7cd96f33838a58c, thanks for reporting.
