### ISSUE TITLE
Name each PD with seL4_DebugNameThread

### ISSUE THREAD

**Issue by midnightveil** [seL4/microkit#235]
It would be useful if microkit setup the names of each thread with `seL4_DebugNameThread()` so that it was obvious which PD caused certain debug prints, e.g.

```c
<<seL4(CPU 0) [decodeInvocation/646 T0x8040278400 "child of: 'rootserver'" @201d28]: Attempted to invoke a null cap #77.>>
```

Could tell us the name of the PD instead of just "child of 'rootserver'".

**Comment by Ivan-Velickovic** [comment]
I was thinking of doing this but wouldn't it just be solved by https://github.com/seL4/microkit/issues/174?

**Comment by Ivan-Velickovic** [comment]
Agreed. Will add this as well then.

**Comment by andybui01** [comment]
The main use for this would be seL4_DebugDumpScheduler would actually display something useful :)

**Comment by Ivan-Velickovic** [comment]
> The main use for this would be seL4_DebugDumpScheduler would actually display something useful :)

When have you found the need to use `seL4_DebugDumpScheduler `?

If it's something people are doing often it means that Microkit should support more debugging infrastructure. I've only used it while developing Microkit from memory.
