### ISSUE TITLE
additional pre-requisites and dependencies for building sdk

### ISSUE THREAD

**Issue by ikuz** [seL4/microkit#6]
Here are some additional tools and packages I had to install to get build_sdk.py to work on a fresh Ubuntu 18.04 install. (these are based on using the initial public release - I notice some more recent updates have added some of the missing python dependencies)

- pandoc: sudo apt install pandoc
- pdflatex: sudo apt install texlive-latex-base
- cmake: sudo apt install cmake - see note below about wrong cmake version
- ninja: sudo apt-get install ninja-build
- gcc-aarch64-linux-gnu: sudo apt-get install gcc-aarch64-linux-gnu
- dtc: sudo apt-get install device-tree-compiler
- pyyaml: ./pyenv/bin/pip install pyyaml
- pyfdt: ./pyenv/bin/pip install pyfdt
- jinja2: ./pyenv/bin/pip install jinja2
- xmllint: ./pyenv/bin/pip install libxml2-utils
- ply: ./pyenv/bin/pip install ply

Note about cmake:
- cmake >= 3.13 is required.  apt installs cmake 3.10.2
- instructions for newer cmakes:
    +  sudo apt-get update
    + sudo apt-get install apt-transport-https ca-certificates gnupg software-properties-common wget
    + wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
    + sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
    + sudo apt-get install cmake

Note about docs: 
- I still got errors trying to build documentation, `Font T1/cmr/m/n/10.95=ecrm1095 at 10.95pt not loadable: Metric (TFM) file not found.`
- so I commented out build_doc and just built the sdk

**Comment by phao5814** [comment]
@ikuz Massive thanks for compiling this list! Saved me a bunch of time when trying to build.

Regarding the following:

> I still got errors trying to build documentation, Font T1/cmr/m/n/10.95=ecrm1095 at 10.95pt not loadable: Metric (TFM) file not found.

I found that sudo apt installing the following fixed those issues:
- `texlive-fonts-recommended`
- `texlive-formats-extra`

Also, `libxml2-utils` should be installed via `apt` instead of `pip` as described below:

> xmllint: ./pyenv/bin/pip install libxml2-utils

In terms of Python dependencies, I also had to install the following packages via `pip`:
- `six`
- `future`

**Comment by perpen** [comment]
Thanks @ikuz and @ptrk8 - I'm on archlinux and resorted to installing all the deps in a container (see https://github.com/perpen/sel4cp-container)
